var express = require('express');
var router = express.Router();
var category = require('../controller/categories');
var customer = require('../controller/customers');
var employee = require('../controller/employees');
var product = require('../controller/products');
var order = require('../controller/orders');
var report = require('../controller/reports');
var top = require('../controller/tops');
var index = require('../controller/index');


router.get('/gian-hang', category.list);
router.get('/dang-nhap', index.login);
router.post('/gian-hang/taomoi', category.create);
router.get('/gian-hang/chuyen-trang-thai/:id', category.changeStatus);
router.get('/nhan-vien', employee.list);
router.get('/nhan-vien/doi-mat-khau', employee.changePassword);
router.post('/nhan-vien/doi-mat-khau', employee.saveNewPassword);
router.post('/nhan-vien', employee.listp);
router.get('/nhan-vien/chuyen-trang-thai/:id', employee.changeStatus);
router.post('/nhan-vien/taomoi', employee.create);
router.get('/khach-hang', customer.list);
router.get('/khach-hang/chuyen-trang-thai/:id', customer.changeStatus);
router.get('/san-pham', product.list);
router.post('/san-pham/taomoi', product.create);
router.get('/san-pham/chuyen-trang-thai/:id', product.changeStatus);
router.get('/don-hang', order.list);
router.get('/don-hang/chuyen-trang-thai/:id', order.changeStatus);
router.get('/thong-ke-bao-cao/ngay', report.day);
router.get('/thong-ke-bao-cao/tuan', report.week);
router.get('/thong-ke-bao-cao/thang', report.month);
router.get('/thong-ke-bao-cao/quy', report.quarter);
router.get('/thong-ke-bao-cao/nam', report.year);
router.get('/tops/san-pham', top.product);
router.get('/tops/gian-hang', top.category);
router.get('/', index.home);
module.exports = router;
